exclude: "test/configs/syntaxerr.py"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-python-dateutil", "types-pytz"]
        files: "^libqtile\/.*"
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.10
    hooks:
      - id: vulture
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.381
    hooks:
    - id: pyright
