name: ci

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-22.04
        name: "Nix ${{ matrix.python-version }} on ${{ matrix.backend }}"
        strategy:
            matrix:
                python-version: ['python310', 'python311', 'python312']
                backend: ['x11', 'wayland']
        steps:
            - uses: actions/checkout@v4
            # if we run dbus-launch for test/widgets/test_bluetooth.py with dbus-launch from nix it doesn't work
            # we need to cheat and use dbus from ubuntu here
            # locally on a NixOS box everything works as expected, so this workaround is only for CI
            - name: Install dbus
              run: sudo apt-get update -y && sudo apt-get install -y dbus-x11
            - uses: cachix/install-nix-action@v26
              # make sure we get no rate limits
              with:
                 github_access_token: ${{ secrets.GITHUB_TOKEN }}
              # cache for Nix, this can get rate limited but if it does CI will not fail
            - uses: DeterminateSystems/magic-nix-cache-action@v2
            - name: run tests in Nix env
              run: nix develop .#test-${{matrix.python-version}} --command qtile-run-tests-${{matrix.backend}}
